# Start the agent nodes to join the cluster
- name: Add servers
  ansible.builtin.service:
    name: rke2-agent.service
    state: restarted
    enabled: true

# Wait for the control plane on server1 to register server 2 and 3 joining the cluster
- name: Verify the rest of the servers are up
  ansible.builtin.command:
    cmd: "kubectl --kubeconfig {{ kubeconfig_path }} get nodes -o wide"
  register: kubectl_nodes
  retries: 10
  delay: 20
  until: "'{{ agent1_ip }}' in kubectl_nodes.stdout and '{{ agent2_ip }}' in kubectl_nodes.stdout"
  changed_when: false
  become: true
  delegate_to: server1
